import type { Listing, Profile } from "./types";

// 당근마켓 스타일 카테고리.
export const CATEGORIES = [
  "디지털기기",
  "생활가전",
  "가구/인테리어",
  "생활/주방",
  "의류",
  "스포츠/레저",
  "뷰티/미용",
  "도서/티켓",
  "반려동물",
  "기타",
] as const;

// 데모 기준 동네: 서울 역삼동 근처.
export const DEFAULT_CENTER = { lat: 37.5006, lng: 127.0365 };

// 데모용 판매자(가짜 지갑 주소). 실제 구매 시 이 주소로 송금되니 데모 글입니다.
const SELLER_A = "0x1111111111111111111111111111111111111111";
const SELLER_B = "0x2222222222222222222222222222222222222222";

export const SEED_SELLERS: Profile[] = [
  {
    address: SELLER_A,
    nickname: "당근천사",
    neighborhood: "역삼동",
    location: { lat: 37.5008, lng: 127.0372 },
    avatar: "🥕",
    mannerTemp: 42.5,
    createdAt: Date.now(),
  },
  {
    address: SELLER_B,
    nickname: "강남이웃",
    neighborhood: "삼성동",
    location: { lat: 37.5102, lng: 127.0561 },
    avatar: "🐰",
    mannerTemp: 38.1,
    createdAt: Date.now(),
  },
];

const HOUR = 60 * 60 * 1000;

type SeedInput = Omit<Listing, "createdAt" | "bumpedAt"> & { agoHours: number };

const RAW: SeedInput[] = [
  {
    id: "seed-1",
    sellerAddress: SELLER_A,
    sellerNickname: "당근천사",
    title: "무선 노이즈캔슬링 헤드폰 거의 새것 팝니다",
    description: "선물받았는데 안 써서 내놔요. 박스/구성품 다 있고 상태 최상입니다.",
    priceBtc: 0.0042,
    category: "디지털기기",
    photoIds: [],
    emoji: "🎧",
    location: { lat: 37.5012, lng: 127.0359 },
    neighborhood: "역삼동",
    status: "selling",
    likes: [],
    agoHours: 1,
  },
  {
    id: "seed-2",
    sellerAddress: SELLER_B,
    sellerNickname: "강남이웃",
    title: "스테인리스 텀블러 1L (새상품)",
    description: "사은품으로 받은 거예요. 미개봉 새 상품입니다.",
    priceBtc: 0.00038,
    category: "생활/주방",
    photoIds: [],
    emoji: "🥤",
    location: { lat: 37.5099, lng: 127.0552 },
    neighborhood: "삼성동",
    status: "selling",
    likes: [],
    agoHours: 3,
  },
  {
    id: "seed-3",
    sellerAddress: SELLER_A,
    sellerNickname: "당근천사",
    title: "기계식 게이밍 키보드 (적축)",
    description: "타건감 좋아요. 사용감 약간 있지만 작동 완벽합니다.",
    priceBtc: 0.0021,
    category: "디지털기기",
    photoIds: [],
    emoji: "⌨️",
    location: { lat: 37.4995, lng: 127.0381 },
    neighborhood: "역삼동",
    status: "reserved",
    likes: [],
    agoHours: 6,
  },
  {
    id: "seed-4",
    sellerAddress: SELLER_B,
    sellerNickname: "강남이웃",
    title: "유기농 원두 1kg 나눔합니다",
    description: "취향에 안 맞아서요. 직거래만 가능, 커피 좋아하시는 분께.",
    priceBtc: 0.00052,
    category: "생활/주방",
    photoIds: [],
    emoji: "☕",
    location: { lat: 37.5121, lng: 127.0578 },
    neighborhood: "삼성동",
    status: "selling",
    likes: [],
    agoHours: 9,
  },
  {
    id: "seed-5",
    sellerAddress: SELLER_A,
    sellerNickname: "당근천사",
    title: "경량 캠핑 의자 2개 일괄",
    description: "캠핑 한 번 가고 보관만 했어요. 접이식, 수납가방 포함.",
    priceBtc: 0.00075,
    category: "스포츠/레저",
    photoIds: [],
    emoji: "🪑",
    location: { lat: 37.5021, lng: 127.0344 },
    neighborhood: "역삼동",
    status: "selling",
    likes: [],
    agoHours: 14,
  },
  {
    id: "seed-6",
    sellerAddress: SELLER_B,
    sellerNickname: "강남이웃",
    title: "고속충전 보조배터리 20000mAh",
    description: "출장용으로 샀다가 잘 안 써서요. C타입 지원.",
    priceBtc: 0.00061,
    category: "디지털기기",
    photoIds: [],
    emoji: "🔋",
    location: { lat: 37.5085, lng: 127.0537 },
    neighborhood: "삼성동",
    status: "selling",
    likes: [],
    agoHours: 20,
  },
  {
    id: "seed-7",
    sellerAddress: SELLER_A,
    sellerNickname: "당근천사",
    title: "프리미엄 요가매트 (논슬립)",
    description: "홈트용으로 잠깐 썼어요. 두께 8mm로 무릎 편합니다.",
    priceBtc: 0.00045,
    category: "스포츠/레저",
    photoIds: [],
    emoji: "🧘",
    location: { lat: 37.4988, lng: 127.0331 },
    neighborhood: "역삼동",
    status: "sold",
    likes: [],
    agoHours: 30,
  },
  {
    id: "seed-8",
    sellerAddress: SELLER_B,
    sellerNickname: "강남이웃",
    title: "스마트 LED 무드등",
    description: "앱으로 색 조절돼요. 책상 위에 두면 분위기 좋아요.",
    priceBtc: 0.00029,
    category: "가구/인테리어",
    photoIds: [],
    emoji: "💡",
    location: { lat: 37.5113, lng: 127.0589 },
    neighborhood: "삼성동",
    status: "selling",
    likes: [],
    agoHours: 40,
  },
];

export const SEED_LISTINGS: Listing[] = RAW.map(({ agoHours, ...l }) => ({
  ...l,
  createdAt: Date.now() - agoHours * HOUR,
  bumpedAt: Date.now() - agoHours * HOUR,
}));
